services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    environment:
      PUBLIC_SITE_URL: ${PUBLIC_SITE_URL:-http://localhost:4321}
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
      - ./packages:/app/packages
      - /app/apps/web/node_modules
      - /app/node_modules
    ports:
      - '4321:4321'
    restart: unless-stopped
