#!/usr/bin/env tsx
/**
 * scripts/okf-link.ts — OKF cross-links codemod (SPEC-DOCS-OKF-001/RF-5, ADR-0015 Fase 3)
 *
 * Usage:
 *   pnpm okf:link                rewrite prose refs in docs/ into bundle links
 *   pnpm okf:link -- --check     warning-only: list linkable refs still in prose (exit 0)
 *   pnpm okf:link <dir>          operate on another bundle root (used by tests)
 *
 * Behavior:
 *   - ID → path map: specs by SPEC-ID in the filename (/specs/SPEC-X-NNN.md),
 *     ADRs by number (ADR-0015 → /adr/0015-….md).
 *   - Per document, the FIRST prose mention of each distinct target becomes a
 *     bundle-absolute link [SPEC-X](/specs/SPEC-X.md) — one relation per doc.
 *   - Untouchable zones: YAML frontmatter, code fences, inline code, existing
 *     markdown links, headings, and self-references (a doc never links itself).
 *   - Refs that do not resolve to an existing file stay in prose and are
 *     reported as warnings (never break the build — RF-5 is permissive).
 *   - Idempotent: re-running produces no changes and never nests links.
 *   - Reserved files (index.md, log.md — INV-2) and the generated
 *     traceability.md (pnpm trace's matrix-gate) are never rewritten.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FRONTMATTER_RE, FENCE_RE, maskInlineCode } from './md-zones';
import { SPEC_ID_RE } from './trace';

const RESERVED = new Set(['index.md', 'log.md']);
// docs/traceability.md is generated by `pnpm trace` and stays the mechanical gate
const GENERATED = new Set(['traceability.md']);

// trace.ts SPEC_ID_RE is ^-anchored for filenames; strip the anchor to scan prose
const SPEC_MENTION_SRC = SPEC_ID_RE.source.replace(/^\^/, '');
const ADR_MENTION_SRC = 'ADR-\\d{4}';
const REF_RE = new RegExp(`${SPEC_MENTION_SRC}|${ADR_MENTION_SRC}`, 'g');

export interface LinkedRef {
  file: string; // bundle-relative doc
  id: string; // e.g. SPEC-QA-001, ADR-0014
  target: string; // bundle-absolute path, e.g. /specs/SPEC-QA-001.md
}

export interface UnresolvedRef {
  file: string;
  id: string;
}

export interface LinkReport {
  changed: string[]; // bundle-relative files rewritten (sorted)
  linked: LinkedRef[];
  unresolved: UnresolvedRef[];
}

// ── ID map ────────────────────────────────────────────────────────────────────

/** Concept ID → bundle-absolute path (SPEC ids from specs/, ADR numbers from adr/). */
export function buildIdMap(bundleRoot: string): Map<string, string> {
  const map = new Map<string, string>();
  const specsDir = path.join(bundleRoot, 'specs');
  if (fs.existsSync(specsDir)) {
    for (const name of fs.readdirSync(specsDir).sort()) {
      if (!name.endsWith('.md') || RESERVED.has(name)) continue;
      const m = SPEC_ID_RE.exec(path.basename(name, '.md'));
      if (m?.[1]) map.set(m[1], `/specs/${name}`);
    }
  }
  const adrDir = path.join(bundleRoot, 'adr');
  if (fs.existsSync(adrDir)) {
    for (const name of fs.readdirSync(adrDir).sort()) {
      if (!name.endsWith('.md') || RESERVED.has(name)) continue;
      const m = /^(\d{4})-/.exec(name);
      if (m?.[1]) map.set(`ADR-${m[1]}`, `/adr/${name}`);
    }
  }
  return map;
}

/** The doc's own concept ID, if it has one (specs and ADRs). */
function selfId(rel: string): string | null {
  const base = path.basename(rel, '.md');
  const spec = SPEC_ID_RE.exec(base);
  if (spec?.[1]) return spec[1];
  const adr = /^(\d{4})-/.exec(base);
  if (adr?.[1] && rel.split(path.sep)[0] === 'adr') return `ADR-${adr[1]}`;
  return null;
}

// ── zone masking ──────────────────────────────────────────────────────────────

/** Blank inline code and existing markdown links, preserving offsets. */
function maskLine(line: string): string {
  // inline code first (backticks bind tighter), then links/images (label + target)
  return maskInlineCode(line).replace(/!?\[[^\]]*\]\([^)]*\)/g, (m) => ' '.repeat(m.length));
}

/** A mention is linkable only as a standalone word, not inside a path or label. */
function boundaryOk(masked: string, start: number, end: number): boolean {
  const prev = start > 0 ? masked[start - 1]! : '';
  if (/[A-Za-z0-9_\-/[\]]/.test(prev)) return false; // word/path/link-label context
  if (masked.startsWith('.md', end)) return false; // filename in prose (…/SPEC-X.md)
  return true;
}

// ── rewrite ───────────────────────────────────────────────────────────────────

interface DocResult {
  content: string;
  linked: { id: string; target: string }[];
  unresolved: string[];
}

export function processDoc(
  content: string,
  map: Map<string, string>,
  own: string | null,
): DocResult {
  // Split off frontmatter (untouchable)
  const fm = FRONTMATTER_RE.exec(content);
  const head = fm ? fm[0] : '';
  const body = content.slice(head.length);

  // Targets already linked anywhere in the doc (absolute or relative form) —
  // one relation per doc: an existing link to a target suppresses new ones.
  const linkedBasenames = new Set<string>();
  for (const m of content.matchAll(/\]\(([^)#\s]+\.md)(?:#[^)]*)?\)/g)) {
    linkedBasenames.add(path.posix.basename(m[1]!));
  }

  const linked: { id: string; target: string }[] = [];
  const unresolved = new Set<string>();
  const done = new Set<string>();
  let inFence = false;

  const lines = body.split('\n').map((line) => {
    if (FENCE_RE.test(line)) {
      inFence = !inFence;
      return line;
    }
    if (inFence || /^\s{0,3}#/.test(line)) return line;

    const masked = maskLine(line);
    let out = '';
    let cursor = 0;
    for (const m of masked.matchAll(REF_RE)) {
      const id = m[0];
      const start = m.index;
      const end = start + id.length;
      if (!boundaryOk(masked, start, end)) continue;
      if (id === own) continue;
      const target = map.get(id);
      if (!target) {
        unresolved.add(id);
        continue;
      }
      if (done.has(id) || linkedBasenames.has(path.posix.basename(target))) continue;
      out += line.slice(cursor, start) + `[${id}](${target})`;
      cursor = end;
      done.add(id);
      linked.push({ id, target });
    }
    return out + line.slice(cursor);
  });

  return { content: head + lines.join('\n'), linked, unresolved: [...unresolved].sort() };
}

// ── bundle walk ───────────────────────────────────────────────────────────────

function collectMdFiles(dir: string, out: string[]): void {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) collectMdFiles(full, out);
    else if (entry.isFile() && entry.name.endsWith('.md')) out.push(full);
  }
}

function processBundle(bundleRoot: string, write: boolean): LinkReport {
  const map = buildIdMap(bundleRoot);
  const report: LinkReport = { changed: [], linked: [], unresolved: [] };

  const files: string[] = [];
  collectMdFiles(bundleRoot, files);
  files.sort();

  for (const file of files) {
    const rel = path.relative(bundleRoot, file);
    const base = path.basename(file);
    if (RESERVED.has(base) || GENERATED.has(rel)) continue;

    const content = fs.readFileSync(file, 'utf-8');
    const res = processDoc(content, map, selfId(rel));

    for (const l of res.linked) report.linked.push({ file: rel, ...l });
    for (const id of res.unresolved) report.unresolved.push({ file: rel, id });

    if (res.content !== content) {
      if (write) fs.writeFileSync(file, res.content, 'utf-8');
      report.changed.push(rel);
    }
  }

  return report;
}

/** Rewrite the bundle in place; returns what changed. */
export function applyLinks(bundleRoot: string): LinkReport {
  return processBundle(bundleRoot, true);
}

/** Dry run: `pending` = linkable refs still in prose (warning-only, never a gate). */
export function checkLinks(bundleRoot: string): {
  pending: LinkedRef[];
  unresolved: UnresolvedRef[];
} {
  const report = processBundle(bundleRoot, false);
  return { pending: report.linked, unresolved: report.unresolved };
}

// ── CLI (always exit 0 — the hard gates remain trace/okf:check) ───────────────
function main(): void {
  const args = process.argv.slice(2).filter((a) => a !== '--');
  const checkMode = args.includes('--check');
  const dirArg = args.find((a) => !a.startsWith('--'));
  const bundleRoot = path.resolve(dirArg ?? path.join(process.cwd(), 'docs'));

  if (checkMode) {
    const { pending, unresolved } = checkLinks(bundleRoot);
    for (const p of pending)
      console.warn(`[okf-link] warn ${p.file}: linkable ref ${p.id} → ${p.target}`);
    for (const u of unresolved)
      console.warn(`[okf-link] warn ${u.file}: unresolved ref ${u.id} (left in prose)`);
    console.log(
      `[okf-link] check — ${pending.length} linkable ref(s) in prose, ${unresolved.length} unresolved.`,
    );
    return; // warning-only by design (no gate duro)
  }

  const report = applyLinks(bundleRoot);
  for (const l of report.linked) console.log(`[okf-link] ${l.file}: ${l.id} → ${l.target}`);
  for (const u of report.unresolved) {
    console.warn(`[okf-link] warn ${u.file}: unresolved ref ${u.id} (left in prose)`);
  }
  console.log(
    `[okf-link] ${report.changed.length} file(s) updated — ${report.linked.length} ref(s) linked, ` +
      `${report.unresolved.length} unresolved.`,
  );
}

const isMain =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
