#!/usr/bin/env tsx
/**
 * scripts/okf-index.ts — OKF progressive-disclosure index generator (SPEC-DOCS-OKF-001/RF-8)
 *
 * Usage:
 *   pnpm okf:index               generate/update index.md in every non-empty docs/ subdir
 *   pnpm okf:index -- --check    verify indexes are up to date (exit 1 if stale)
 *   pnpm okf:index <dir>         operate on another bundle root (used by tests)
 *
 * Per OKF §6:
 *   - Each non-empty subdirectory of the bundle root gets an index.md catalog:
 *     bullets `* [Title](file.md) - description` from each concept's frontmatter.
 *   - Indexes are reserved files: NO frontmatter (only the bundle-root index.md
 *     carries frontmatter, and only okf_version — INV-2).
 *   - The root index.md links every sub-index inside a managed marker block;
 *     prose outside the block is preserved.
 *   - Output is deterministic (sorted by filename) so reruns produce no diff.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

export const GENERATED_MARK = '<!-- generated by okf:index — do not edit; run `pnpm okf:index` -->';
export const ROOT_BLOCK_START = '<!-- okf:index:start -->';
export const ROOT_BLOCK_END = '<!-- okf:index:end -->';

const RESERVED = new Set(['index.md', 'log.md']);
const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;

interface ConceptMeta {
  file: string; // basename, e.g. SPEC-A11Y-001.md
  title: string;
  description?: string;
  type?: string;
}

function readMeta(filePath: string): ConceptMeta {
  const content = fs.readFileSync(filePath, 'utf-8');
  const file = path.basename(filePath);
  const meta: ConceptMeta = { file, title: path.basename(filePath, '.md') };
  const m = FRONTMATTER_RE.exec(content);
  if (!m) return meta;
  try {
    const data = YAML.parse(m[1]!) as Record<string, unknown> | null;
    if (typeof data?.['title'] === 'string' && data['title'].trim()) meta.title = data['title'];
    if (typeof data?.['description'] === 'string' && data['description'].trim()) {
      meta.description = data['description'];
    }
    if (typeof data?.['type'] === 'string' && data['type'].trim()) meta.type = data['type'];
  } catch {
    // unparseable frontmatter is okf-check's problem (RF-2); index falls back to filename
  }
  return meta;
}

// Non-empty = has ≥1 direct non-reserved .md (same rule as okf-check RF-8)
function listSubdirs(bundleRoot: string): string[] {
  return fs
    .readdirSync(bundleRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((dir) => conceptFiles(path.join(bundleRoot, dir)).length > 0)
    .sort();
}

function conceptFiles(dir: string): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md') && !RESERVED.has(e.name))
    .map((e) => e.name)
    .sort();
}

function subIndexContent(bundleRoot: string, sub: string): string {
  const dir = path.join(bundleRoot, sub);
  const bullets = conceptFiles(dir).map((f) => {
    const meta = readMeta(path.join(dir, f));
    return meta.description
      ? `* [${meta.title}](${f}) - ${meta.description}`
      : `* [${meta.title}](${f})`;
  });
  return [GENERATED_MARK, '', `# ${sub}/`, '', ...bullets, ''].join('\n');
}

function rootBlockContent(bundleRoot: string, subdirs: string[]): string {
  const lines = subdirs.map((sub) => {
    const files = conceptFiles(path.join(bundleRoot, sub));
    const types = [
      ...new Set(
        files
          .map((f) => readMeta(path.join(bundleRoot, sub, f)).type)
          .filter((t): t is string => typeof t === 'string'),
      ),
    ].sort();
    const typeNote = types.length > 0 ? ` · type: ${types.join(', ')}` : '';
    return `- **[${sub}/](/${sub}/index.md)** — ${files.length} concepto${files.length === 1 ? '' : 's'}${typeNote}`;
  });
  return lines.join('\n');
}

function rootIndexContent(bundleRoot: string, subdirs: string[]): string {
  const rootIndex = path.join(bundleRoot, 'index.md');
  const current = fs.readFileSync(rootIndex, 'utf-8');
  const start = current.indexOf(ROOT_BLOCK_START);
  const end = current.indexOf(ROOT_BLOCK_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `okf-index: root index.md lacks the managed block markers ` +
        `${ROOT_BLOCK_START} … ${ROOT_BLOCK_END}`,
    );
  }
  const before = current.slice(0, start + ROOT_BLOCK_START.length);
  const after = current.slice(end);
  return `${before}\n${rootBlockContent(bundleRoot, subdirs)}\n${after}`;
}

/** Desired content per target file (bundle-relative path → content). */
export function buildIndexes(bundleRoot: string): Map<string, string> {
  const out = new Map<string, string>();
  const subdirs = listSubdirs(bundleRoot);
  for (const sub of subdirs) {
    out.set(path.join(sub, 'index.md'), subIndexContent(bundleRoot, sub));
  }
  out.set('index.md', rootIndexContent(bundleRoot, subdirs));
  return out;
}

/** Write stale indexes; returns the bundle-relative paths that changed. */
export function applyIndexes(bundleRoot: string): string[] {
  const changed: string[] = [];
  for (const [rel, content] of buildIndexes(bundleRoot)) {
    const full = path.join(bundleRoot, rel);
    const current = fs.existsSync(full) ? fs.readFileSync(full, 'utf-8') : null;
    if (current !== content) {
      fs.writeFileSync(full, content, 'utf-8');
      changed.push(rel);
    }
  }
  return changed.sort();
}

/** Returns the bundle-relative paths whose on-disk content is stale/missing. */
export function checkIndexes(bundleRoot: string): string[] {
  const stale: string[] = [];
  for (const [rel, content] of buildIndexes(bundleRoot)) {
    const full = path.join(bundleRoot, rel);
    if (!fs.existsSync(full) || fs.readFileSync(full, 'utf-8') !== content) stale.push(rel);
  }
  return stale.sort();
}

// ── CLI ───────────────────────────────────────────────────────────────────────
function main(): void {
  const args = process.argv.slice(2).filter((a) => a !== '--');
  const checkMode = args.includes('--check');
  const dirArg = args.find((a) => !a.startsWith('--'));
  const bundleRoot = path.resolve(dirArg ?? path.join(process.cwd(), 'docs'));

  if (checkMode) {
    const stale = checkIndexes(bundleRoot);
    if (stale.length > 0) {
      for (const rel of stale) console.error(`[okf-index] STALE ${rel}`);
      console.error('[okf-index] FAIL: indexes out of date — run `pnpm okf:index`.');
      process.exit(1);
    }
    console.log('[okf-index] OK — all indexes up to date.');
    return;
  }

  const changed = applyIndexes(bundleRoot);
  for (const rel of changed) console.log(`[okf-index] wrote ${rel}`);
  console.log(`[okf-index] ${changed.length} file(s) updated.`);
}

const isMain =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
