/**
 * security-headers — pure header logic for SPEC-SEC-016/RF-1 (F-02, ADR-0018).
 * Kept free of any `astro:*` import so it's directly unit-testable; the Astro
 * middleware glue (src/middleware.ts) is a thin wrapper around this module.
 *
 * CSP itself is NOT built here: it's generated by Astro's `experimental.csp`
 * at render time (astro.config.ts) and arrives on `response` already set by
 * the time the middleware sees it — see prompt 61 (fixed a perf regression
 * from an earlier version that read+hashed the response body per request).
 */

export const STATIC_SECURITY_HEADERS: Record<string, string> = {
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
};

/** /admin is Access-gated and CDN-loaded — never gets the strict site CSP. */
export function isExemptPath(pathname: string): boolean {
  return pathname.startsWith('/admin');
}

/**
 * Astro's experimental.csp auto-hashes every inline `<style>` block it
 * compiles — including scoped styles from the ~22 flat, pre-ADR-0012
 * components not yet migrated to CSS Modules (that migration is its own,
 * separate effort; not in scope here). Per the CSP spec, a hash's mere
 * *presence* in `style-src` silently revokes `'unsafe-inline'` for the whole
 * directive (`style-src-attr` included) — breaking every dynamic
 * `style="..."` attribute sitewide, which ADR-0018 explicitly accepts via
 * `unsafe-inline` as a trade-off. Astro's *script* hashes have no such
 * problem (no inline event-handler-attribute equivalent in this codebase),
 * so we keep those and only strip style hashes — a plain string edit on the
 * already-built header value: O(header size), not O(HTML) (RNF-2). This
 * self-obsoletes once those components migrate to CSS Modules (Astro then
 * emits no style hash and this becomes a no-op).
 */
export function stripStyleHashesFromCsp(csp: string): string {
  return csp.replace(/style-src(?:-attr|-elem)?[^;]*/g, (segment) =>
    segment.replace(/\s*'sha(?:256|384|512)-[^']+'/g, ''),
  );
}

/**
 * Pure decision of which (non-CSP) headers to apply, given the request path,
 * the response's content-type, and the runtime SITE_ENV. Returns null when no
 * headers should be added (non-document response, or an exempt path). O(1) —
 * no body access, no regex over HTML, no hashing (RNF-2).
 */
export function headersFor(
  pathname: string,
  contentType: string | null,
  siteEnv: string | undefined,
): Record<string, string> | null {
  if (isExemptPath(pathname)) return null;
  if (!(contentType ?? '').includes('text/html')) return null;

  const headers = { ...STATIC_SECURITY_HEADERS };
  if (siteEnv === 'staging') {
    headers['X-Robots-Tag'] = 'noindex, nofollow';
  }
  return headers;
}
